/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import core.AppContext;
import entity.Admin;
import entity.Manufacturer;
import entity.Report;
import entity.Retailer;
import entity.Role;
import entity.Shipment;
import entity.Shipper;
import entity.User;
import entity.WarehouseManager;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author SkyPC
 */
public class AdminUI extends javax.swing.JPanel {
    private final AppContext context;
    private final JFrame parentFrame;

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        this.context = null;
        this.parentFrame = null;
        initComponents();
        wireLogic();
    }

    public AdminUI(AppContext context, JFrame parentFrame) {
        this.context = context;
        this.parentFrame = parentFrame;
        initComponents();
        wireLogic();
    }

    public static JFrame createFrame(AppContext context, JFrame parentFrame) {
        JFrame frame = new JFrame("SCTS - Admin Panel");
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setSize(980, 860);
        frame.setLocationRelativeTo(null);
        frame.setLayout(new BorderLayout());
        frame.setContentPane(new AdminUI(context, parentFrame));
        return frame;
    }

    private void wireLogic() {
        jLabel2.setText("Admin can manage users (add/delete), view shipments, and generate reports.");
        jLabel3.setText("User ID");
        jLabel4.setText("Name");
        jLabel5.setText("Email");
        jLabel8.setText("Password");
        jLabel7.setText("Role");
        jLabel6.setText("Role Detail");
        jLabel9.setText("Delete User ID");
        jLabel10.setText("Role Detail: company/org/contact/warehouseId (depends on role)");
        ResultViewer.setEditable(false);
        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{
            Role.ADMIN.name(),
            Role.MANUFACTURER.name(),
            Role.SHIPPER.name(),
            Role.WAREHOUSE_MANAGER.name(),
            Role.RETAILER.name()
        }));

        if (context == null) {
            setInteractive(false);
            return;
        }

        ViewUsers.addActionListener(e -> viewUsers());
        ViewShipments.addActionListener(e -> viewShipments());
        AddUser.addActionListener(e -> addUser());
        GenerateReport.addActionListener(e -> generateReport());
        DeleteUser.addActionListener(e -> deleteUser());
        BackToDashboard.addActionListener(e -> goBack());
    }

    private void setInteractive(boolean enabled) {
        ViewUsers.setEnabled(enabled);
        ViewShipments.setEnabled(enabled);
        AddUser.setEnabled(enabled);
        GenerateReport.setEnabled(enabled);
        BackToDashboard.setEnabled(enabled);
        DeleteUser.setEnabled(enabled);
        jComboBox1.setEnabled(enabled);
        jTextField1.setEnabled(enabled);
        jTextField2.setEnabled(enabled);
        jTextField3.setEnabled(enabled);
        jTextField4.setEnabled(enabled);
        jTextField5.setEnabled(enabled);
        jTextField6.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ViewUsers = new javax.swing.JButton();
        ViewShipments = new javax.swing.JButton();
        AddUser = new javax.swing.JButton();
        GenerateReport = new javax.swing.JButton();
        BackToDashboard = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        DeleteUser = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultViewer = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("System Administration");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Admin can manage users (add/delete)");

        ViewUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewUsers.setText("View Users");

        ViewShipments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewShipments.setText("View Shipments");

        AddUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddUser.setText("Add User");

        GenerateReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenerateReport.setText("Generate Report");
        GenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportActionPerformed(evt);
            }
        });

        BackToDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToDashboard.setText("Back to Dashboard");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("User ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Role Detail");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Role");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Delete User ID");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteUser.setText("Delete User");

        jLabel10.setText("NOTE: Role detail ex: company/org/etc");

        jLabel11.setText("Result Viewer");

        ResultViewer.setColumns(20);
        ResultViewer.setRows(5);
        jScrollPane1.setViewportView(ResultViewer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ViewShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteUser))
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportActionPerformed
        generateReport();
    }//GEN-LAST:event_GenerateReportActionPerformed

    private void viewUsers() {
        ResultViewer.setText("Users:\n");
        List<User> users = context.adminControl.viewAllUsers();
        for (User user : users) {
            ResultViewer.append(user.getUserId() + " | " + user.getRole() + " | " + user.getName() + " | " + user.getEmail() + "\n");
        }
    }

    private void viewShipments() {
        ResultViewer.setText("Shipments:\n");
        List<Shipment> shipments = context.adminControl.viewAllShipments();
        for (Shipment shipment : shipments) {
            ResultViewer.append(shipment.getShipmentId() + " | " + shipment.getPickupLocation() + " -> " + shipment.getDestination() + "\n");
        }
    }

    private void addUser() {
        try {
            String userId = required(jTextField1.getText(), "User ID");
            String name = required(jTextField2.getText(), "Name");
            String email = required(jTextField3.getText(), "Email");
            String password = required(jTextField4.getText(), "Password");
            String selectedRole = jComboBox1.getSelectedItem() == null ? "" : jComboBox1.getSelectedItem().toString();
            Role role = Role.valueOf(selectedRole);
            String roleDetail = jTextField5.getText() == null ? "" : jTextField5.getText().trim();

            User user = buildUser(userId, name, email, password, role, roleDetail);
            context.adminControl.addUser(user);
            ResultViewer.setText("User created: " + user.getUserId() + " (" + user.getRole() + ")\n");
            clearAddForm();
            viewUsers();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Add user failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteUser() {
        try {
            String userId = required(jTextField6.getText(), "Delete User ID");
            context.adminControl.deleteUser(userId);
            ResultViewer.setText("User deleted: " + userId + "\n");
            jTextField6.setText("");
            viewUsers();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Delete user failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void generateReport() {
        try {
            Report report = context.adminControl.generateSystemReport();
            ResultViewer.setText("Report generated:\nID: " + report.getReportId()
                    + "\nGenerated At: " + report.getGeneratedAt()
                    + "\nTotal Events: " + report.getIncludedEvents().size());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Generate report failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private User buildUser(String userId, String name, String email, String password, Role role, String roleDetail) {
        return switch (role) {
            case ADMIN -> new Admin(userId, name, email, password, true, roleDetail.isBlank() ? "SYSTEM" : roleDetail);
            case MANUFACTURER -> new Manufacturer(userId, name, email, password, true, roleDetail.isBlank() ? "Company" : roleDetail);
            case SHIPPER -> new Shipper(userId, name, email, password, true,
                    roleDetail.isBlank() ? "Shipper Co" : roleDetail,
                    "N/A", true);
            case WAREHOUSE_MANAGER -> new WarehouseManager(userId, name, email, password, true, roleDetail);
            case RETAILER -> new Retailer(userId, name, email, password, true,
                    roleDetail.isBlank() ? "Retail Org" : roleDetail,
                    "Unknown");
        };
    }

    private void clearAddForm() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }

    private String required(String value, String fieldName) {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException(fieldName + " is required.");
        }
        return value.trim();
    }

    private void goBack() {
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof JFrame frame) {
            Navigation.goBack(frame, parentFrame);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUser;
    private javax.swing.JButton BackToDashboard;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JButton GenerateReport;
    private javax.swing.JTextArea ResultViewer;
    private javax.swing.JButton ViewShipments;
    private javax.swing.JButton ViewUsers;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
