/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import core.AppContext;
import entity.Role;
import entity.User;

/**
 *
 * @author SkyPC
 */
public class DashboardFrame extends javax.swing.JFrame {
    private final AppContext context;
    private final User currentUser;

    /**
     * Creates new form DashboardFrame2
     */
    public DashboardFrame() {
        this.context = null;
        this.currentUser = null;
        initComponents();
        wireLogic();
    }

    public DashboardFrame(AppContext context, User currentUser) {
        this.context = context;
        this.currentUser = currentUser;
        initComponents();
        wireLogic();
    }

    private void wireLogic() {
        setLocationRelativeTo(null);
        if (currentUser == null) {
            Welcome.setText("Welcome,");
            role.setText("Role:");
            ShipmentManagement.setEnabled(false);
            GoodsManagement.setEnabled(false);
            InventoryManagement.setEnabled(false);
            VehicleManagement.setEnabled(false);
            AdminPanel.setEnabled(false);
            return;
        }

        Welcome.setText("Welcome, " + currentUser.getName());
        role.setText("Role: " + currentUser.getRole());
        GoodsManagement.setEnabled(currentUser.getRole() == Role.MANUFACTURER);
        VehicleManagement.setEnabled(currentUser.getRole() == Role.SHIPPER);
        InventoryManagement.setEnabled(currentUser.getRole() == Role.WAREHOUSE_MANAGER);
        AdminPanel.setEnabled(currentUser.getRole() == Role.ADMIN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        ShipmentManagement = new javax.swing.JButton();
        GoodsManagement = new javax.swing.JButton();
        InventoryManagement = new javax.swing.JButton();
        VehicleManagement = new javax.swing.JButton();
        AdminPanel = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("Welcome, ");
        getContentPane().add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 351, 34));

        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("Role: ");
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 46, 293, -1));

        ShipmentManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ShipmentManagement.setText("Shipment Management");
        ShipmentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipmentManagementActionPerformed(evt);
            }
        });
        getContentPane().add(ShipmentManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 293, 62));

        GoodsManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GoodsManagement.setText("Manufacturer Goods Management");
        GoodsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodsManagementActionPerformed(evt);
            }
        });
        getContentPane().add(GoodsManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 300, 62));

        InventoryManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InventoryManagement.setText("Warehouse Inventory Management");
        InventoryManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryManagementActionPerformed(evt);
            }
        });
        getContentPane().add(InventoryManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 300, 62));

        VehicleManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VehicleManagement.setText("Vehicle Management");
        VehicleManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleManagementActionPerformed(evt);
            }
        });
        getContentPane().add(VehicleManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 293, 62));

        AdminPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminPanel.setText("Admin Panel");
        AdminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPanelActionPerformed(evt);
            }
        });
        getContentPane().add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 293, 62));

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 300, 62));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AdobeStock_1075519100.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShipmentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipmentManagementActionPerformed
        if (context == null || currentUser == null) {
            return;
        }
        Navigation.openChild(this, new ShipmentManagementUI(context, currentUser, this));
    }//GEN-LAST:event_ShipmentManagementActionPerformed

    private void GoodsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodsManagementActionPerformed
        if (context == null || currentUser == null) {
            return;
        }
        Navigation.openChild(this, new ManufacturerGoodsManagementUI(context, currentUser, this));
    }//GEN-LAST:event_GoodsManagementActionPerformed

    private void InventoryManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryManagementActionPerformed
        if (context == null || currentUser == null) {
            return;
        }
        Navigation.openChild(this, new WarehouseInventoryManagementUI(context, currentUser, this));
    }//GEN-LAST:event_InventoryManagementActionPerformed

    private void VehicleManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleManagementActionPerformed
        if (context == null || currentUser == null) {
            return;
        }
        Navigation.openChild(this, VehicleManagementUI.createFrame(context, currentUser, this));
    }//GEN-LAST:event_VehicleManagementActionPerformed

    private void AdminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPanelActionPerformed
        if (context == null || currentUser == null) {
            return;
        }
        Navigation.openChild(this, AdminUI.createFrame(context, this));
    }//GEN-LAST:event_AdminPanelActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        if (context == null) {
            dispose();
            return;
        }
        context.authenticationControl.logout();
        new LoginUI(context).setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminPanel;
    private javax.swing.JButton GoodsManagement;
    private javax.swing.JButton InventoryManagement;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ShipmentManagement;
    private javax.swing.JButton VehicleManagement;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel role;
    // End of variables declaration//GEN-END:variables
}
