/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import core.AppContext;
import entity.DeliveryEvidence;
import entity.Role;
import entity.Shipment;
import entity.User;
import entity.Vehicle;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pattern.strategy.FragileGoodsInspectionStrategy;
import pattern.strategy.HazardousInspectionStrategy;
import pattern.strategy.StandardInspectionStrategy;

/**
 *
 * @author SkyPC
 */
public class EventRecordingFrame extends javax.swing.JFrame {
    private final AppContext context;
    private final User currentUser;
    private final JFrame parentFrame;
    private final String prefilledShipmentId;

    /**
     * Creates new form EventRecordingFrame2
     */
    public EventRecordingFrame() {
        this.context = null;
        this.currentUser = null;
        this.parentFrame = null;
        this.prefilledShipmentId = null;
        initComponents();
        wireLogic();
    }

    public EventRecordingFrame(AppContext context, User currentUser, JFrame parentFrame) {
        this(context, currentUser, parentFrame, null);
    }

    public EventRecordingFrame(AppContext context, User currentUser, JFrame parentFrame, String prefilledShipmentId) {
        this.context = context;
        this.currentUser = currentUser;
        this.parentFrame = parentFrame;
        this.prefilledShipmentId = prefilledShipmentId;
        initComponents();
        wireLogic();
    }

    private void wireLogic() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        jLabel5.setText("Event Recording");
        StatusLabel.setText("Current Shipment Status: -");
        jTextArea1.setEditable(false);
        jTextArea1.setText(context == null || currentUser == null ? "Open from dashboard/login context." : buildRoleGuideText(currentUser.getRole()));
        BackToDashboard.addActionListener(e -> Navigation.goBack(this, parentFrame));
        RecordEvent.addActionListener(e -> recordEvent());
        ShipmentComboBox.addActionListener(e -> reloadEventTypesForSelectedShipment());

        if (context == null || currentUser == null) {
            setInteractive(false);
            return;
        }
        loadVisibleShipments();
        reloadEventTypesForSelectedShipment();
    }

    private void setInteractive(boolean enabled) {
        ShipmentComboBox.setEnabled(enabled);
        EventTypeComboBox.setEnabled(enabled);
        DescriptionBox.setEnabled(enabled);
        RecordEvent.setEnabled(enabled);
        BackToDashboard.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ShipmentComboBox = new javax.swing.JComboBox<>();
        StatusLabel = new javax.swing.JLabel();
        EventTypeComboBox = new javax.swing.JComboBox<>();
        DescriptionBox = new javax.swing.JTextField();
        RecordEvent = new javax.swing.JButton();
        BackToDashboard = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Goods Management");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Shipment");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Current Status");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Event Type");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Description");

        ShipmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        StatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusLabel.setText("Current Shipment Status: ");

        EventTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RecordEvent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RecordEvent.setText("Record Event");

        BackToDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToDashboard.setText("Back to Dashboard");

        jLabel6.setText("Role Guide");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RecordEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(BackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EventTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DescriptionBox)
                            .addComponent(ShipmentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ShipmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EventTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DescriptionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecordEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadVisibleShipments() {
        try {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            List<Shipment> shipments = context.shipmentControl.getVisibleShipments(currentUser);
            for (Shipment shipment : shipments) {
                model.addElement(shipment.getShipmentId());
            }
            ShipmentComboBox.setModel(model);
            if (prefilledShipmentId != null && !prefilledShipmentId.isBlank()) {
                ShipmentComboBox.setSelectedItem(prefilledShipmentId);
            } else if (model.getSize() > 0) {
                ShipmentComboBox.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load shipments: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reloadEventTypesForSelectedShipment() {
        try {
            String shipmentId = selectedShipmentId();
            if (shipmentId == null || shipmentId.isBlank()) {
                EventTypeComboBox.setModel(new DefaultComboBoxModel<>());
                StatusLabel.setText("Current Shipment Status: -");
                return;
            }

            String status = context.shipmentControl.viewShipmentStatus(currentUser, shipmentId);
            StatusLabel.setText("Current Shipment Status: " + status);

            List<String> validEvents = context.shipmentControl.getAllowedEventsForShipment(currentUser, shipmentId);
            DefaultComboBoxModel<String> eventModel = new DefaultComboBoxModel<>();
            for (String e : validEvents) {
                eventModel.addElement(e);
            }
            EventTypeComboBox.setModel(eventModel);
            if (eventModel.getSize() > 0) {
                EventTypeComboBox.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to refresh event options: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void recordEvent() {
        String shipmentId = selectedShipmentId();
        String eventType = (String) EventTypeComboBox.getSelectedItem();
        String notes = DescriptionBox.getText().trim();

        if (shipmentId == null || shipmentId.isBlank()) {
            JOptionPane.showMessageDialog(this, "Select a shipment first.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (eventType == null || eventType.isBlank()) {
            JOptionPane.showMessageDialog(this, "No valid event is currently available for this shipment state.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            switch (eventType) {
                case "SHIPMENT_ACCEPTED" -> context.eventControl.recordShipmentAcceptanceEvent(currentUser, shipmentId);
                case "DISPATCH" -> {
                    String vehicleId = required(prompt("Vehicle ID"), "Vehicle ID");
                    Vehicle vehicle = new Vehicle(vehicleId, "TRUCK", "TEMP-123", 100, "AVAILABLE");
                    context.eventControl.recordDispatchEvent(currentUser, shipmentId, vehicle);
                }
                case "RECEIPT" -> context.eventControl.recordReceiptEvent(currentUser, shipmentId, defaultIfEmpty(notes, "GOOD"));
                case "INSPECTION" -> {
                    setInspectionStrategyFromPrompt();
                    context.eventControl.recordInspectionEvent(currentUser, shipmentId, defaultIfEmpty(notes, "Inspection completed"));
                }
                case "STORAGE" -> context.eventControl.recordStorageEvent(currentUser, shipmentId, defaultIfEmpty(notes, "Zone A"));
                case "DELIVERY" -> {
                    String evidence = required(prompt("Evidence path"), "Evidence path");
                    DeliveryEvidence deliveryEvidence = new DeliveryEvidence(
                            "E-" + UUID.randomUUID(),
                            evidence,
                            LocalDateTime.now(),
                            "UNVERIFIED");
                    context.eventControl.recordDeliveryEvent(currentUser, shipmentId, deliveryEvidence);
                }
                case "DELAY" -> context.eventControl.recordDelayEvent(currentUser, shipmentId, defaultIfEmpty(notes, "Traffic"));
                case "DELIVERY_CONFIRMATION" -> context.shipmentControl.recordDeliveryConfirmation(currentUser, shipmentId, defaultIfEmpty(notes, "Confirmed by retailer"));
                case "FAILED_DELIVERY" -> {
                    String reason = required(defaultIfEmpty(notes, ""), "Failure reason");
                    String evidence = required(prompt("Evidence path"), "Evidence path");
                    context.shipmentControl.reportFailedDelivery(currentUser, shipmentId, reason, evidence);
                }
                case "RETURN_REQUESTED" -> {
                    String reason = required(defaultIfEmpty(notes, ""), "Return reason");
                    String evidence = required(prompt("Evidence path"), "Evidence path");
                    context.shipmentControl.requestShipmentReturn(currentUser, shipmentId, reason, evidence);
                }
                case "RETURN_DISPATCHED" -> {
                    String vehicleId = required(prompt("Vehicle ID"), "Vehicle ID");
                    context.eventControl.recordReturnDispatchEvent(currentUser, shipmentId, vehicleId);
                }
                case "RETURNED" -> {
                    Shipment shipment = context.shipmentControl.findShipmentById(currentUser, shipmentId);
                    String warehouseId = shipment.getSourceWarehouseId();
                    if (warehouseId == null || warehouseId.isBlank()) {
                        warehouseId = "UNKNOWN";
                    }
                    context.eventControl.recordReturnedEvent(currentUser, shipmentId, warehouseId);
                }
                default -> throw new IllegalArgumentException("Unknown event type.");
            }
            JOptionPane.showMessageDialog(this, "Event recorded successfully.");
            reloadEventTypesForSelectedShipment();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to record event: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String selectedShipmentId() {
        Object selected = ShipmentComboBox.getSelectedItem();
        return selected == null ? null : selected.toString();
    }

    private String defaultIfEmpty(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }

    private String required(String value, String fieldName) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(fieldName + " is required.");
        }
        return value.trim();
    }

    private String prompt(String title) {
        return JOptionPane.showInputDialog(this, title + ":", title, JOptionPane.PLAIN_MESSAGE);
    }

    private String buildRoleGuideText(Role role) {
        return switch (role) {
            case SHIPPER -> "You can record: SHIPMENT_ACCEPTED, DISPATCH, DELIVERY, DELAY, FAILED_DELIVERY, RETURN_DISPATCHED";
            case WAREHOUSE_MANAGER -> "You can record: RECEIPT, INSPECTION, STORAGE, RETURNED";
            case RETAILER -> "You can record: DELIVERY_CONFIRMATION, RETURN_REQUESTED";
            default -> "No event recording permissions for this role.";
        };
    }

    private void setInspectionStrategyFromPrompt() {
        Object selected = JOptionPane.showInputDialog(
                this,
                "Inspection Strategy:",
                "Select Strategy",
                JOptionPane.PLAIN_MESSAGE,
                null,
                new Object[]{"STANDARD", "FRAGILE", "HAZARDOUS"},
                "STANDARD");
        String strategy = selected == null ? "STANDARD" : selected.toString();
        if ("FRAGILE".equals(strategy)) {
            context.eventControl.setStrategy(new FragileGoodsInspectionStrategy());
        } else if ("HAZARDOUS".equals(strategy)) {
            context.eventControl.setStrategy(new HazardousInspectionStrategy());
        } else {
            context.eventControl.setStrategy(new StandardInspectionStrategy());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventRecordingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventRecordingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventRecordingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventRecordingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventRecordingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToDashboard;
    private javax.swing.JTextField DescriptionBox;
    private javax.swing.JComboBox<String> EventTypeComboBox;
    private javax.swing.JButton RecordEvent;
    private javax.swing.JComboBox<String> ShipmentComboBox;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
