/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import core.AppContext;
import entity.Good;
import entity.Manufacturer;
import entity.Role;
import entity.User;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SkyPC
 */
public class ManufacturerGoodsManagementUI extends javax.swing.JFrame {
    private final AppContext context;
    private final User currentUser;
    private final JFrame parentFrame;
    private final List<Good> currentGoods;
    private final DefaultTableModel goodsModel;

    /**
     * Creates new form GoodsManagementUI
     */
    public ManufacturerGoodsManagementUI() {
        this.context = null;
        this.currentUser = null;
        this.parentFrame = null;
        this.currentGoods = new ArrayList<>();
        this.goodsModel = new DefaultTableModel(new Object[]{"Good ID", "Label", "Description", "Weight", "Volume", "Stock", "Warehouse"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        initComponents();
        wireLogic();
    }

    public ManufacturerGoodsManagementUI(AppContext context, User currentUser, JFrame parentFrame) {
        if (currentUser.getRole() != Role.MANUFACTURER) {
            throw new IllegalArgumentException("Access denied: only Manufacturer can open Goods Management.");
        }
        this.context = context;
        this.currentUser = currentUser;
        this.parentFrame = parentFrame;
        this.currentGoods = new ArrayList<>();
        this.goodsModel = new DefaultTableModel(new Object[]{"Good ID", "Label", "Description", "Weight", "Volume", "Stock", "Warehouse"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        initComponents();
        wireLogic();
    }

    private void wireLogic() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        jTable1.setModel(goodsModel);
        if (context == null || currentUser == null) {
            setInteractive(false);
            return;
        }
        RegisterGood.addActionListener(e -> registerGood());
        RemoveSelected.addActionListener(e -> removeSelectedGood());
        IncreaseStock.addActionListener(e -> adjustSelectedGoodStock(true));
        DecreaseStock.addActionListener(e -> adjustSelectedGoodStock(false));
        RefreshList1.addActionListener(e -> reloadGoodsList());
        BacktoDashboard1.addActionListener(e -> Navigation.goBack(this, parentFrame));
        ManufacturerComboBox.addActionListener(e -> reloadGoodsList());
        loadManufacturers();
        reloadGoodsList();
    }

    private void setInteractive(boolean enabled) {
        ManufacturerComboBox.setEnabled(enabled);
        LabelField.setEnabled(enabled);
        DescriptionField.setEnabled(enabled);
        WeightField.setEnabled(enabled);
        VolumeField.setEnabled(enabled);
        VolumeField1.setEnabled(enabled);
        RegisterGood.setEnabled(enabled);
        RemoveSelected.setEnabled(enabled);
        IncreaseStock.setEnabled(enabled);
        DecreaseStock.setEnabled(enabled);
        RefreshList1.setEnabled(enabled);
        BacktoDashboard1.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ManufacturerComboBox = new javax.swing.JComboBox<>();
        LabelField = new javax.swing.JTextField();
        DescriptionField = new javax.swing.JTextField();
        WeightField = new javax.swing.JTextField();
        VolumeField = new javax.swing.JTextField();
        RegisterGood = new javax.swing.JButton();
        RemoveSelected = new javax.swing.JButton();
        IncreaseStock = new javax.swing.JButton();
        DecreaseStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        VolumeField1 = new javax.swing.JTextField();
        BacktoDashboard1 = new javax.swing.JButton();
        RefreshList1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manufacturer");

        jLabel2.setText("Label");

        jLabel3.setText("Weight");

        jLabel4.setText("Description");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Manufacturer Goods Management");

        jLabel6.setText("Volume");

        ManufacturerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RegisterGood.setText("Register Good");

        RemoveSelected.setText("Remove Selected");

        IncreaseStock.setText("Increase Stock");

        DecreaseStock.setText("Decrease Stock");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Goods List");

        jLabel8.setText("Quantity Change (+/-)");

        VolumeField1.setText("1");

        BacktoDashboard1.setText("Back to Dashboard");

        RefreshList1.setText("Refresh List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VolumeField)
                            .addComponent(WeightField)
                            .addComponent(DescriptionField)
                            .addComponent(ManufacturerComboBox, 0, 341, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(VolumeField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegisterGood, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(RemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IncreaseStock, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(DecreaseStock, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RefreshList1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(BacktoDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManufacturerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolumeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterGood, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IncreaseStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecreaseStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefreshList1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BacktoDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadManufacturers() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        try {
            for (Manufacturer manufacturer : context.goodControl.listSelectableManufacturers(currentUser)) {
                model.addElement(manufacturer.getUserId());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load manufacturers: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        ManufacturerComboBox.setModel(model);
        ManufacturerComboBox.setEnabled(false);
        if (model.getSize() > 0) {
            ManufacturerComboBox.setSelectedIndex(0);
        }
    }

    private void registerGood() {
        try {
            String manufacturerId = selectedManufacturerId();
            manufacturerId = context.goodControl.resolveManagedManufacturerId(currentUser, manufacturerId);
            Manufacturer manufacturer = findManufacturer(manufacturerId);
            if (manufacturer == null) {
                throw new IllegalArgumentException("Manufacturer not found.");
            }

            String goodId = "G-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
            Good good = new Good(
                    goodId,
                    required(LabelField.getText(), "Label"),
                    required(DescriptionField.getText(), "Description"),
                    manufacturer,
                    Double.parseDouble(required(WeightField.getText(), "Weight")),
                    Double.parseDouble(required(VolumeField.getText(), "Volume")));

            context.goodControl.registerGood(currentUser, good);
            clearForm();
            reloadGoodsList();
            JOptionPane.showMessageDialog(this, "Good registered with ID: " + goodId);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Register failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void removeSelectedGood() {
        try {
            Good good = selectedGood();
            context.goodControl.removeGood(currentUser, good.getGoodId());
            reloadGoodsList();
            JOptionPane.showMessageDialog(this, "Removed good: " + good.getGoodId());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Remove failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void adjustSelectedGoodStock(boolean increase) {
        try {
            Good good = selectedGood();
            int amount = Integer.parseInt(required(VolumeField1.getText(), "Quantity"));
            if (!increase) {
                amount = -Math.abs(amount);
            }
            String manufacturerId = good.getManufacturer().getUserId();
            int newStock = context.goodControl.adjustGoodQuantity(currentUser, manufacturerId, good.getGoodId(), amount);
            reloadGoodsList();
            String action = increase ? "increased" : "decreased";
            JOptionPane.showMessageDialog(this, "Stock " + action + ". New stock: " + newStock);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Quantity update failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reloadGoodsList() {
        if (context == null || currentUser == null) {
            return;
        }
        try {
            goodsModel.setRowCount(0);
            currentGoods.clear();

            String manufacturerId = context.goodControl.resolveManagedManufacturerId(currentUser, selectedManufacturerId());
            List<Good> goods = context.goodControl.listGoodsByManufacturer(currentUser, manufacturerId);
            String warehouseId = context.goodControl.resolveManufacturerWarehouse(manufacturerId);

            for (Good good : goods) {
                int stock = context.goodControl.getGoodStock(currentUser, manufacturerId, good.getGoodId());
                currentGoods.add(good);
                goodsModel.addRow(new Object[]{
                    good.getGoodId(),
                    good.getLabel(),
                    good.getDescription(),
                    good.getWeight(),
                    good.getVolume(),
                    stock,
                    warehouseId == null ? "-" : warehouseId
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load goods list: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Good selectedGood() {
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            throw new IllegalArgumentException("Select a good from the list first.");
        }
        return currentGoods.get(row);
    }

    private String selectedManufacturerId() {
        Object selected = ManufacturerComboBox.getSelectedItem();
        return selected == null ? null : selected.toString();
    }

    private Manufacturer findManufacturer(String manufacturerId) {
        for (User user : context.userRepository.findAllUsers()) {
            if (user.getRole() == Role.MANUFACTURER && user.getUserId().equalsIgnoreCase(manufacturerId)) {
                return (Manufacturer) user;
            }
        }
        return null;
    }

    private String required(String value, String fieldName) {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException(fieldName + " is required.");
        }
        return value.trim();
    }

    private void clearForm() {
        LabelField.setText("");
        DescriptionField.setText("");
        WeightField.setText("");
        VolumeField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManufacturerGoodsManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManufacturerGoodsManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManufacturerGoodsManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManufacturerGoodsManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManufacturerGoodsManagementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoDashboard1;
    private javax.swing.JButton DecreaseStock;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JButton IncreaseStock;
    private javax.swing.JTextField LabelField;
    private javax.swing.JComboBox<String> ManufacturerComboBox;
    private javax.swing.JButton RefreshList1;
    private javax.swing.JButton RegisterGood;
    private javax.swing.JButton RemoveSelected;
    private javax.swing.JTextField VolumeField;
    private javax.swing.JTextField VolumeField1;
    private javax.swing.JTextField WeightField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
