/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import core.AppContext;
import entity.Role;
import entity.Shipper;
import entity.User;
import entity.Vehicle;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SkyPC
 */
public class VehicleManagementUI extends javax.swing.JPanel {
    private final AppContext context;
    private final User currentUser;
    private final JFrame parentFrame;
    private final List<Vehicle> currentVehicles;
    private final DefaultTableModel vehicleModel;

    /**
     * Creates new form VehicleManagementUI2
     */
    public VehicleManagementUI() {
        this.context = null;
        this.currentUser = null;
        this.parentFrame = null;
        this.currentVehicles = new ArrayList<>();
        this.vehicleModel = new DefaultTableModel(new Object[]{"Vehicle ID", "Type", "Plate", "Capacity", "Status"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        initComponents();
        wireLogic();
    }

    public VehicleManagementUI(AppContext context, User currentUser, JFrame parentFrame) {
        if (currentUser.getRole() != Role.SHIPPER) {
            throw new IllegalArgumentException("Access denied: only Shipper can open Vehicle Management.");
        }
        this.context = context;
        this.currentUser = currentUser;
        this.parentFrame = parentFrame;
        this.currentVehicles = new ArrayList<>();
        this.vehicleModel = new DefaultTableModel(new Object[]{"Vehicle ID", "Type", "Plate", "Capacity", "Status"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        initComponents();
        wireLogic();
    }

    public static JFrame createFrame(AppContext context, User currentUser, JFrame parentFrame) {
        JFrame frame = new JFrame("SCTS - Vehicle Management");
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setSize(1000, 760);
        frame.setLocationRelativeTo(null);
        frame.setLayout(new BorderLayout());
        frame.setContentPane(new VehicleManagementUI(context, currentUser, parentFrame));
        return frame;
    }

    private void wireLogic() {
        jTable1.setModel(vehicleModel);
        jComboBox5.setModel(new DefaultComboBoxModel<>(new String[]{"AVAILABLE", "IN_USE", "MAINTENANCE"}));
        if (context == null || currentUser == null) {
            setInteractive(false);
            return;
        }

        addVehicle.addActionListener(e -> addVehicleAction());
        RemoveSelected.addActionListener(e -> removeSelectedVehicle());
        UpdateSelectedStatus.addActionListener(e -> updateSelectedStatus());
        RefreshList.addActionListener(e -> reloadVehicleList());
        BackToDashboard.addActionListener(e -> goBack());
        jComboBox1.addActionListener(e -> reloadVehicleList());

        loadShippers();
        reloadVehicleList();
    }

    private void setInteractive(boolean enabled) {
        jComboBox1.setEnabled(enabled);
        jTextField1.setEnabled(enabled);
        jTextField2.setEnabled(enabled);
        jTextField3.setEnabled(enabled);
        jComboBox5.setEnabled(enabled);
        addVehicle.setEnabled(enabled);
        RemoveSelected.setEnabled(enabled);
        UpdateSelectedStatus.setEnabled(enabled);
        RefreshList.setEnabled(enabled);
        BackToDashboard.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        addVehicle = new javax.swing.JButton();
        RemoveSelected = new javax.swing.JButton();
        RefreshList = new javax.swing.JButton();
        UpdateSelectedStatus = new javax.swing.JButton();
        BackToDashboard = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Vehicle Management");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Manage shipper vehicles");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Shipper");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Vehicle Type");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("License Plate");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Capacity");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Status");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        addVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addVehicle.setText("Add Vehicle");

        RemoveSelected.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveSelected.setText("Remove Selected");

        RefreshList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RefreshList.setText("Refresh List");

        UpdateSelectedStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateSelectedStatus.setText("Update Selected Status");

        BackToDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToDashboard.setText("Back to Dashboard");

        jLabel8.setText("Vehicle List");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(692, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpdateSelectedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RefreshList, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateSelectedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshList, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void loadShippers() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(currentUser.getUserId());
        jComboBox1.setEnabled(false);
        jComboBox1.setModel(model);
        if (model.getSize() > 0) {
            jComboBox1.setSelectedIndex(0);
        }
    }

    private void addVehicleAction() {
        try {
            Shipper shipper = selectedShipper();
            if (shipper == null) {
                throw new IllegalArgumentException("Select a valid shipper.");
            }

            Vehicle vehicle = new Vehicle(
                    "V-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase(),
                    required(jTextField1.getText(), "Vehicle type"),
                    required(jTextField2.getText(), "License plate"),
                    Integer.parseInt(required(jTextField3.getText(), "Capacity")),
                    jComboBox5.getSelectedItem().toString());

            context.vehicleControl.addVehicle(currentUser, shipper, vehicle);
            clearForm();
            reloadVehicleList();
            JOptionPane.showMessageDialog(this, "Vehicle added: " + vehicle.getVehicleId());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Add failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void removeSelectedVehicle() {
        try {
            int row = jTable1.getSelectedRow();
            if (row < 0) {
                throw new IllegalArgumentException("Select a vehicle from the list first.");
            }
            Shipper shipper = selectedShipper();
            if (shipper == null) {
                throw new IllegalArgumentException("Select a valid shipper.");
            }
            Vehicle selected = currentVehicles.get(row);
            context.vehicleControl.removeVehicle(currentUser, shipper, selected);
            reloadVehicleList();
            JOptionPane.showMessageDialog(this, "Removed vehicle: " + selected.getVehicleId());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Remove failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateSelectedStatus() {
        try {
            int row = jTable1.getSelectedRow();
            if (row < 0) {
                throw new IllegalArgumentException("Select a vehicle from the list first.");
            }
            Shipper shipper = selectedShipper();
            if (shipper == null) {
                throw new IllegalArgumentException("Select a valid shipper.");
            }
            Vehicle selected = currentVehicles.get(row);
            String status = jComboBox5.getSelectedItem().toString();
            context.vehicleControl.updateVehicleStatus(currentUser, shipper.getUserId(), selected, status);
            reloadVehicleList();
            JOptionPane.showMessageDialog(this, "Updated " + selected.getVehicleId() + " to " + status);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Update failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reloadVehicleList() {
        if (context == null || currentUser == null) {
            return;
        }
        try {
            vehicleModel.setRowCount(0);
            currentVehicles.clear();
            Shipper shipper = selectedShipper();
            if (shipper == null) {
                return;
            }
            List<Vehicle> vehicles = context.vehicleControl.retrieveAllVehicles(currentUser, shipper.getUserId());
            for (Vehicle vehicle : vehicles) {
                currentVehicles.add(vehicle);
                vehicleModel.addRow(new Object[]{
                    vehicle.getVehicleId(),
                    vehicle.getVehicleType(),
                    vehicle.getLicensePlate(),
                    vehicle.getCapacity(),
                    vehicle.getStatus()
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load vehicle list: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Shipper selectedShipper() {
        Object selected = jComboBox1.getSelectedItem();
        if (selected == null) {
            return null;
        }
        String shipperId = selected.toString();
        for (User user : context.userRepository.findAllUsers()) {
            if (user.getRole() == Role.SHIPPER && user.getUserId().equalsIgnoreCase(shipperId)) {
                return (Shipper) user;
            }
        }
        return null;
    }

    private String required(String value, String fieldName) {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException(fieldName + " is required.");
        }
        return value.trim();
    }

    private void clearForm() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox5.setSelectedItem("AVAILABLE");
    }

    private void goBack() {
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof JFrame frame) {
            Navigation.goBack(frame, parentFrame);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToDashboard;
    private javax.swing.JButton RefreshList;
    private javax.swing.JButton RemoveSelected;
    private javax.swing.JButton UpdateSelectedStatus;
    private javax.swing.JButton addVehicle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
