/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import core.AppContext;
import entity.Good;
import entity.Item;
import entity.Role;
import entity.User;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SkyPC
 */
public class WarehouseInventoryManagementUI extends javax.swing.JFrame {
    private final AppContext context;
    private final User currentUser;
    private final JFrame parentFrame;
    private final List<Item> currentItems;
    private final DefaultTableModel inventoryModel;

    /**
     * Creates new form InventoryManagementUI
     */
    public WarehouseInventoryManagementUI() {
        this.context = null;
        this.currentUser = null;
        this.parentFrame = null;
        this.currentItems = new ArrayList<>();
        this.inventoryModel = new DefaultTableModel(new Object[]{"Item ID", "Good ID", "Good Label", "Quantity", "Manufacture Date"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        initComponents();
        wireLogic();
    }

    public WarehouseInventoryManagementUI(AppContext context, User currentUser, JFrame parentFrame) {
        if (currentUser.getRole() != Role.WAREHOUSE_MANAGER) {
            throw new IllegalArgumentException("Access denied: only Warehouse Manager can open Inventory Management.");
        }
        this.context = context;
        this.currentUser = currentUser;
        this.parentFrame = parentFrame;
        this.currentItems = new ArrayList<>();
        this.inventoryModel = new DefaultTableModel(new Object[]{"Item ID", "Good ID", "Good Label", "Quantity", "Manufacture Date"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        initComponents();
        wireLogic();
    }

    private void wireLogic() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        WarehouseInventoryListTable.setModel(inventoryModel);
        if (context == null || currentUser == null) {
            setInteractive(false);
            return;
        }

        jButton2.addActionListener(e -> increaseSelected());
        jButton3.addActionListener(e -> decreaseSelected());
        jButton4.addActionListener(e -> reloadInventoryList());
        jButton5.addActionListener(e -> Navigation.goBack(this, parentFrame));
        WarehouseComboBox.addActionListener(e -> reloadInventoryList());

        loadWarehouses();
        loadGoods();
        reloadInventoryList();
    }

    private void setInteractive(boolean enabled) {
        WarehouseComboBox.setEnabled(enabled);
        GoodComboBox.setEnabled(enabled);
        QuantityField.setEnabled(enabled);
        WarehouseInventoryListTable.setEnabled(enabled);
        jButton1.setEnabled(enabled);
        jButton2.setEnabled(enabled);
        jButton3.setEnabled(enabled);
        jButton4.setEnabled(enabled);
        jButton5.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        WarehouseComboBox = new javax.swing.JComboBox<>();
        GoodComboBox = new javax.swing.JComboBox<>();
        QuantityField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        WarehouseInventoryListTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Warehouse Inventory Management");

        jLabel2.setText("Warehouse");

        jLabel3.setText("Good");

        jLabel4.setText("Quantity");

        WarehouseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Store New Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Increase Selected");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Decrease Selected");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Refresh List");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Back to Dashboard");

        jLabel5.setText("Warehouse Inventory List");

        WarehouseInventoryListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(WarehouseInventoryListTable);

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Store and adjust warehouse stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 38, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(214, 214, 214)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WarehouseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GoodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(QuantityField))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(WarehouseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(GoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        storeItem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadWarehouses() {
        try {
            List<String> ids = context.inventoryControl.listVisibleWarehouses(currentUser);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (String id : ids) {
                model.addElement(id);
            }
            WarehouseComboBox.setModel(model);
            WarehouseComboBox.setEnabled(false);
            if (model.getSize() > 0) {
                WarehouseComboBox.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load warehouses: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadGoods() {
        try {
            List<Good> goods = context.goodControl.listVisibleGoods(currentUser);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Good good : goods) {
                model.addElement(good.getGoodId() + " - " + good.getLabel());
            }
            GoodComboBox.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load goods: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void storeItem() {
        if (context == null || currentUser == null) {
            return;
        }
        try {
            String warehouseId = selectedWarehouse();
            String goodId = selectedGoodId();
            int quantity = Integer.parseInt(required(QuantityField.getText(), "Quantity"));
            String itemId = "I-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();

            context.inventoryControl.storeItem(currentUser, warehouseId, itemId, goodId, quantity);
            reloadInventoryList();
            JOptionPane.showMessageDialog(this, "Stored item " + itemId + " in warehouse " + warehouseId);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Store failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void increaseSelected() {
        try {
            int row = WarehouseInventoryListTable.getSelectedRow();
            if (row < 0) {
                throw new IllegalArgumentException("Select an inventory item first.");
            }
            Item item = currentItems.get(row);
            int quantity = Integer.parseInt(required(QuantityField.getText(), "Quantity"));
            context.inventoryControl.increaseStock(currentUser, selectedWarehouse(), item.getItemId(), item.getGood().getGoodId(), quantity);
            reloadInventoryList();
            JOptionPane.showMessageDialog(this, "Stock increased for item: " + item.getItemId());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Increase failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void decreaseSelected() {
        try {
            int row = WarehouseInventoryListTable.getSelectedRow();
            if (row < 0) {
                throw new IllegalArgumentException("Select an inventory item first.");
            }
            Item item = currentItems.get(row);
            int quantity = Integer.parseInt(required(QuantityField.getText(), "Quantity"));
            context.inventoryControl.decreaseStock(currentUser, selectedWarehouse(), item.getItemId(), quantity);
            reloadInventoryList();
            JOptionPane.showMessageDialog(this, "Stock decreased for item: " + item.getItemId());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Decrease failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reloadInventoryList() {
        if (context == null || currentUser == null) {
            return;
        }
        try {
            String warehouseId = selectedWarehouse();
            if (warehouseId == null || warehouseId.isBlank()) {
                return;
            }
            inventoryModel.setRowCount(0);
            currentItems.clear();
            List<Item> items = context.inventoryControl.viewInventory(currentUser, warehouseId);
            for (Item item : items) {
                currentItems.add(item);
                inventoryModel.addRow(new Object[]{
                    item.getItemId(),
                    item.getGood().getGoodId(),
                    item.getGood().getLabel(),
                    item.getQuantity(),
                    item.getManufactureDate()
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load inventory list: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String selectedWarehouse() {
        Object selected = WarehouseComboBox.getSelectedItem();
        return selected == null ? null : selected.toString();
    }

    private String selectedGoodId() {
        Object selected = GoodComboBox.getSelectedItem();
        if (selected == null) {
            throw new IllegalArgumentException("Select a good.");
        }
        return selected.toString().split(" - ")[0];
    }

    private String required(String value, String fieldName) {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException(fieldName + " is required.");
        }
        return value.trim();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehouseInventoryManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehouseInventoryManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehouseInventoryManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseInventoryManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehouseInventoryManagementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GoodComboBox;
    private javax.swing.JTextField QuantityField;
    private javax.swing.JComboBox<String> WarehouseComboBox;
    private javax.swing.JTable WarehouseInventoryListTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
